import { test, expect } from '@playwright/test'
import { readFile } from 'node:fs/promises'
const catalogue=JSON.parse(await readFile('public/catalogue/products.json','utf8'))
const adminPath='/hdhdhdhhdhdcurioo'

test('real FRP filters, quantities and WhatsApp destination',async({page})=>{
 await page.route('**/api/catalogue',route=>route.fulfill({json:catalogue}))
 await page.goto('/')
 await expect(page.getByTestId('product-card')).toHaveCount(12)
 await expect(page.getByTestId('product-card').first().locator('.product-tags')).toContainText('12 × 12 inch')
 const sizeOptions = await page.getByLabel('Size', { exact: true }).locator('option').allTextContents()
 expect(sizeOptions.indexOf('375 × 375 mm')).toBeLessThan(sizeOptions.indexOf('15 × 15 inch'))
 expect(sizeOptions.indexOf('600 × 600 mm')).toBeLessThan(sizeOptions.indexOf('24 × 24 inch'))
 await page.getByLabel('Load capacity',{exact:true}).selectOption('5 ton')
 await page.getByLabel('Size',{exact:true}).selectOption('24 × 24 inch')
 const matching=catalogue.products.filter((p:any)=>p.load_capacity==='5 ton'&&p.size==='24 × 24 inch')
 await expect(page.getByTestId('product-card')).toHaveCount(matching.length)
 const first=page.getByTestId('product-card').first()
 await first.getByRole('button',{name:/Increase/}).click({clickCount:2})
 await first.getByRole('button',{name:/Decrease/}).click()
 await expect(first.locator('output')).toHaveText('2')
 const link=new URL((await first.getByRole('link',{name:'Buy on WhatsApp'}).getAttribute('href'))!)
 expect(link.pathname).toBe('/917990907899')
 for(const text of ['Quantity: 2','5 ton','24 × 24 inch']) expect(link.searchParams.get('text')).toContain(text)
 await page.getByLabel('Load capacity',{exact:true}).selectOption('40 ton')
 await expect(page.getByLabel('Size',{exact:true})).toHaveValue('')
 await expect(page.getByTestId('product-card')).toHaveCount(catalogue.products.filter((p:any)=>p.load_capacity==='40 ton').length)
 await page.getByRole('button',{name:'Clear filters'}).click()
 await page.getByRole('button',{name:'Page 2',exact:true}).click()
 await page.getByLabel('Load capacity',{exact:true}).selectOption('20 ton')
 await expect(page.getByRole('button',{name:'Page 1',exact:true})).toHaveAttribute('aria-current','page')
})

for(const width of [320,390,768,1440]) {
 test(`Fibro catalogue and online add/edit admin at ${width}px`,async({page})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
  let products=structuredClone(catalogue.products);let revision=0
  await page.route('**/api/catalogue**',async route=>{
   const action=new URL(route.request().url()).searchParams.get('action')
   if(action==='session') return route.fulfill({json:{authenticated:true,email:'admin@example.test'}})
   if(action==='save') {
    const form=await new Response(route.request().postDataBuffer(),{headers:{'Content-Type':route.request().headers()['content-type']}}).formData()
    const input=JSON.parse(String(form.get('product')))
    products=products.map((p:any)=>p.id===input.id?{...p,...input}:p);revision++
   }
   return route.fulfill({json:{version:1,revision,products}})
  })
  await page.setViewportSize({width,height:1000});await page.goto('/')
  await expect(page.getByTestId('product-card')).toHaveCount(12)
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  await page.goto(adminPath)
  await page.getByRole('button',{name:`Edit ${products[0].title}`,exact:true}).first().click()
  const dialog=page.getByRole('dialog')
  await expect(dialog.locator('legend').filter({hasText:'Description'})).toBeVisible()
  await page.getByLabel('Load capacity',{exact:true}).fill('60 ton')
  await page.getByLabel('Size',{exact:true}).fill('800 × 800 mm')
  await page.getByLabel('Clear opening',{exact:true}).fill('700 × 700 mm')
  await page.getByLabel('Frame size',{exact:true}).fill('800 × 800 mm')
  await page.getByLabel('Cover size',{exact:true}).fill('750 × 750 mm')
  expect(await dialog.evaluate(el=>el.scrollWidth<=el.clientWidth)).toBe(true)
  await page.screenshot({path:`test-results/fibro-admin-edit-${width}.png`,fullPage:true})
  await page.getByRole('button',{name:'Save product',exact:true}).click()
  await expect(dialog).toHaveCount(0)
  await page.reload()
  await page.getByRole('button',{name:`Edit ${products[0].title}`,exact:true}).first().click()
  await expect(page.getByLabel('Cover size',{exact:true})).toHaveValue('750 × 750 mm')
  await page.getByRole('button',{name:'Cancel',exact:true}).click()
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  await page.screenshot({path:`test-results/fibro-admin-${width}.png`,fullPage:true})
  await page.getByRole('button',{name:'Add product',exact:true}).click()
  await expect(page.locator('#capacity-options option[value="60 ton"]')).toHaveCount(1)
  await expect(page.locator('#size-options option[value="800 × 800 mm"]')).toHaveCount(1)
  await expect(page.getByLabel('Clear opening',{exact:true})).toHaveValue('')
  await page.getByRole('button',{name:'Cancel',exact:true}).click()
  await page.goto('/')
  await page.getByLabel('Load capacity',{exact:true}).selectOption('60 ton')
  await page.getByLabel('Size',{exact:true}).selectOption('800 × 800 mm')
  await expect(page.getByTestId('product-card')).toHaveCount(1)
  await expect(page.getByTestId('product-card')).toContainText('750 × 750 mm')
  await page.screenshot({path:`test-results/fibro-filtered-${width}.png`,fullPage:true})
  expect(errors).toEqual([])
 })
}
